# Generated by Django 4.0.3 on 2022-03-31 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listenports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracks',
            options={'verbose_name': 'POI', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterField(
            model_name='tracks',
            name='accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='Точность'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='alt',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='bearing',
            field=models.FloatField(blank=True, null=True, verbose_name='Азимут'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='tracker_id',
            field=models.IntegerField(verbose_name='ИД трекера'),
        ),
        migrations.CreateModel(
            name='Trackers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.IntegerField(verbose_name='ИД трекера')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('resend', models.BooleanField(default=False, verbose_name='Переслать на livegpstracks.com')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Трекер',
                'verbose_name_plural': 'Трекеры',
            },
        ),
        migrations.AddField(
            model_name='tracks',
            name='tracker_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listenports.trackers', verbose_name='Трекер'),
        ),
    ]
